from pathlib import Path
import json,hashlib,collections,csv,io,shutil
H=Path(__file__).resolve().parent;P=Path(r'C:\JeonghyunPark\Workspace\QSTL_24DC_4MW_PCB\QSTL_24DC_4MW_PCB');D=P/'docs'
reports={f:json.loads((H/f).read_text()) for f in ['native_validation.json','angle_validation.json','stubless_validation.json','central_validation.json','preservation_validation.json']}
digest=hashlib.sha256((P/'QSTL_24DC_4MW_PCB.PcbDoc').read_bytes()).hexdigest();assert all(r['passed'] and r['pcb_sha256']==digest for r in reports.values())
n=json.loads((H/'native_render_snapshot.json').read_text());assert n['source_sha256']==digest
v=reports['native_validation.json'];dc=reports['central_validation.json'];plan=json.loads((H/'dc_routes.json').read_text());sch=json.loads((H/'schematic_final_validation.json').read_text());assert sch['passed'] and sch['native_compile']['complete']
v.update(DC_routing_audit='DC_direct.json',RF_routing_layer=6,RF_Altium_layer_ID=32,RF_impedance_verified=False,ground_polygons=3,DC_central_parallel_gap_mm=dc['central_edge_gap_min_mm'],DC_cross_layer_overlap_mm=dc['overlapping_centreline_length_across_L2_L4_mm'],DC_retained_layer_transition_via=dc['retained_transition_via'],DC_vias_added_this_revision=0,DC_pin_changes=plan['pin_changes'],RF_stubless_audit=dict(passed=True,report='RF_stubless.json'),RF_position_and_angle_audit=dict(passed=True,report='RF_position_and_angles.json'),native_schematic_compile_summary=sch['native_compile']['summary'],native_schematic_compile_note='The API returns False with zero reported violations, as in the previous revision. All 33 named nets and 41 intentional singleton NC nets were exported and independently matched to the saved PCB. The Boolean is not reported as a successful compiler result.')
stack=json.loads((D/'RF_surface_stack.json').read_text())['order_from_QD_side'];v['copper_stack_from_QD_side']=stack
(D/'validation.json').write_text(json.dumps(v,indent=2)+'\n')
report=dict(passed=True,pcb_sha256=digest,order_from_QD_side=stack,central_DC_nets_by_layer={str(l):[t['net'] for t in dc['central_lanes_by_layer'][str(l)]] for l in [2,4]},DC_secondary_layer_segments=dict(ZIF23='Short L4 escape transitions to main L2 at (13.35,16.4) mm'),tracks_by_layer=dict(collections.Counter(t['layer'] for t in n['tracks'])),RF_layer=6,RF_Altium_layer_ID=32,RF_width_mm=next(t['width'] for t in n['tracks'] if t['layer']==32),DC_width_mm=.125,Top_ZIF_escape_width_mm=.15,ground_layers=[1,3,5],ground_polygon_count=3,stack_material_and_thickness_unchanged=True,RF_impedance_verified=False,impedance_note='No fabrication-stack 50-ohm verification has been performed.',DRC=v['DRC_after_save_and_reopen'],DC_routing_audit='DC_direct.json')
(D/'RF_surface_stack.json').write_text(json.dumps(report,indent=2)+'\n')
delay=json.loads((D/'RF_delay.json').read_text());delay['pcb_sha256']=digest;(D/'RF_delay.json').write_text(json.dumps(delay,indent=2)+'\n')
rows=list(csv.DictReader((D/'PIN_MAPPING.csv').read_text().splitlines()));columns=list(rows[0])
for r in rows:
 target=(r['Bias_resistor']+'-2') if r['Role']=='RF+DC_bias' else 'Q1-'+r['QD_pad']
 z=next(z for z,t in plan['zif_to_target'].items() if t==target);r['ZIF_pin']=z;r['Reference_carrier_bond_pad']=str(int(z)-(2 if int(z)>=15 else 0))
 if r['Role']=='DC':r['QD_net']=f'ZIF{int(z):02d}'
out=io.StringIO(newline='');writer=csv.DictWriter(out,columns,lineterminator='\n');writer.writeheader();writer.writerows(rows);(D/'PIN_MAPPING.csv').write_text(out.getvalue())
assert len({r['ZIF_pin'] for r in rows})==24
shutil.copy2(P/'work/dc_direct_schematic_compile.txt',D/'native_schematic_compile.txt')
readme=(H/'README.before.md').read_text()
readme=readme.replace('The schematic, libraries and project membership are unchanged.','DC assignments now use ZIF17 to QD3, ZIF19 to QD2 and ZIF21 to R1 pin2 (QD9 bias), moving the R1 branch to the outside of its routing bundle. The original SchDoc and QD symbol pin names in SchLib have been updated to match; project membership and footprint geometry are unchanged.')
start=readme.index('DC now uses overlapping');end=readme.index(' Straight tracks',start)
readme=readme[:start]+'''DC uses overlapping L2/L4 routes through the centre of the board. Each layer has 12 parallel routes at the same XY positions over y=18-30 mm, spanning x=6.15-12.75 mm. The pitch is 0.6 mm and the copper edge gap is approximately 0.475 mm. The full design retains the 0.15 mm clearance rule; the measured DC trace-to-trace minimum on the same layer is approximately 0.175 mm. Crossings between different layers are intentional; through-hole pads and vias remain obstacles on both layers. The retained 0.5/0.25 mm through via at (13.35,16.4) changes ZIF23 from a short L4 escape to its main L2 route. No vias were added in this revision. The QD branches now stay in the central bundle until y=35.1 mm, close to QD. R1 bias branches from the outside lane, so unrelated DC traces no longer weave through the R1/C1 via field. The minimum copper gap between those vias and unrelated DC is approximately 0.588 mm. This removes 64 internal track segments (305 to 241) and about 2.51 mm of total planar DC route length. DC width is 0.125 mm and Top escapes are 0.15 mm. Top ZIF escapes, RF copper, component placement and stack dimensions remain unchanged. [Routing comparison](QSTL_24DC_4MW_PCB/docs/DC_direct_comparison.png), [DC audit](QSTL_24DC_4MW_PCB/docs/DC_direct.json), [DC-only view](QSTL_24DC_4MW_PCB/docs/DC_only.png) and [separated routing layers](QSTL_24DC_4MW_PCB/docs/Routing_layers.png) show the result.'''+readme[end:]
readme=readme.replace('docs/DC_centered_DRC.html','docs/DC_direct_DRC.html').replace("Current PCB pins agree with the unchanged schematic's 33 named nets and 41 intentional singleton NC nets.","Current PCB pins agree with the updated schematic's 33 named nets and 41 intentional singleton NC nets. The native schematic compiler API still returns `False` with zero reported violations, as in the preceding revision; its complete exported connectivity agrees with the saved PCB. This Boolean is retained in the validation report rather than treated as a successful compiler result.")
(P.parent/'README.md').write_text(readme,encoding='utf-8')
print(json.dumps(dict(pcb_sha256=digest,reports_updated=True,pin_mapping_rows=len(rows),schematic_connectivity_matches=True,native_compile_summary=sch['native_compile']['summary']),indent=2))
